name: Sync images

on:
  workflow_dispatch:
#  schedule:
#    # every day at 7am & 7pm pacific
#    - cron: "0 2,14 * * *"
  push:
    branches:
      - main

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./auth.yaml
          images_file: ./images.yaml
          version: latest
          proc: 20
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          CCR_USERNAME: ${{ secrets.CCR_USERNAME }}
          CCR_PASSWORD: ${{ secrets.CCR_PASSWORD }}